const $=s=>document.querySelector(s);let ws=null,deferred=null,lastState=null;
const stored=localStorage.getItem('wiiew_api');
const API=()=>{const v=localStorage.getItem('wiiew_api')||localStorage.getItem('wiiew_backend_url');if(v)return v.replace(/\/$/,'');if(location.hostname.endsWith('github.io'))return '';return location.origin};
const apiPath=p=>`${API()}${p}`;
const wsPath=()=>{const base=API();if(!base)return '';const u=new URL(base);u.protocol=u.protocol==='https:'?'wss:':'ws:';return `${u.origin}/ws/live`};
function setConn(ok){const e=$('#connection');e.classList.toggle('online',ok);e.innerHTML=`<i></i> ${ok?'Live':'Offline'}`}
function fmtAgo(v){if(v==null)return'—';if(v<5)return'just now';if(v<60)return`${Math.floor(v)}s ago`;return`${Math.floor(v/60)}m ago`}
function render(s){lastState=s;const r=s.room||{},p=s.phone||{},sen=s.sensor||{},sys=s.system||{};const hero=$('#hero'),title=$('#state-title'),text=$('#state-text'),person=$('#person'),label=$('#visual-label');hero.className='hero';
 if(!sys.armed){hero.classList.add('empty');title.textContent=r.sustained_presence?'Presence detected':'Monitoring paused';text.textContent='System is disarmed.';label.textContent=r.sustained_presence?'PRESENCE':'PAUSED'}
 else if(r.state==='PRESENCE_UNTRUSTED'||r.state==='PRESENCE_DETECTED_INTRUDER'){hero.classList.add('intruder');title.textContent='Someone is here';text.textContent='Someone has entered your room.';label.textContent='PRESENCE DETECTED'}
 else if(r.state==='PRESENCE_TRUSTED'||r.state==='PRESENCE_DETECTED_SUPPRESSED'){hero.classList.add('suppressed');title.textContent='You are home';text.textContent='Trusted phone present — alert suppressed.';label.textContent='TRUSTED DEVICE'}
 else if(r.state==='CHECKING_PRESENCE'||(r.raw_presence&&!r.sustained_presence)){hero.classList.add('empty');title.textContent='Checking…';text.textContent='Confirming a real presence before alerting you.';label.textContent='CONFIRMING'}
 else if(r.state==='SENSOR_OFFLINE'){hero.classList.add('empty');title.textContent='Sensor offline';text.textContent='CSI sensor is offline.';label.textContent='OFFLINE'}
 else{hero.classList.add('empty');title.textContent='Room empty';text.textContent='Nothing detected right now.';label.textContent='CLEAR'}
 const confirm=$('#confirm');if(r.raw_presence&&!r.sustained_presence&&sys.armed){confirm.hidden=false;const d=r.presence_duration_seconds||0,t=r.presence_threshold_seconds||15;$('#confirm-fill').style.width=`${Math.min(100,d/t*100)}%`;$('#confirm-time').textContent=`${Math.floor(d)}s / ${t}s`}else confirm.hidden=true;
 $('#sensor').textContent=sen.online?'Online':'Offline';$('#server').textContent=sen.online?'Online':'Offline';$('#sensor-dot').className=`dot ${sen.online?'online':''}`;$('#server-dot').className=`dot ${sen.online?'online':''}`;
 $('#phone').textContent=!p.configured?'Not set':p.is_home?'Home':'Away';$('#phone-dot').className=`dot ${p.is_home?'online':''}`;
 $('#arm').querySelector('span:nth-child(2)').textContent=sys.armed?'ARMED':'DISARMED';$('#arm').style.background=sys.armed?'linear-gradient(135deg,#173e31,#11271f)':'rgba(255,255,255,.045)';
 $('#last').textContent=`Last activity ${fmtAgo(r.last_activity_seconds_ago)}`;$('#motion').textContent=`Motion ${r.motion_level||'—'}`;$('#signal-meta').textContent=`${sen.rssi_dbm??'—'} dBm · ${sen.subcarriers?.length||0} tones`;
 const bars=$('#bars'),amps=sen.subcarriers||[];if(bars.children.length!==amps.slice(0,52).length){bars.innerHTML='';amps.slice(0,52).forEach(()=>{const i=document.createElement('i');bars.appendChild(i)})}const max=Math.max(1,...amps.slice(0,52));[...bars.children].forEach((b,i)=>b.style.height=`${Math.max(8,amps[i]/max*68)}px`)
}
async function status(){try{const r=await fetch(apiPath('/api/status'));if(!r.ok)throw 0;render(await r.json());setConn(true)}catch{setConn(false)}}
function connect(){const url=wsPath();if(!url){setConn(false);return}try{ws?.close()}catch{}ws=new WebSocket(url);ws.onopen=()=>setConn(true);ws.onmessage=e=>{try{render(JSON.parse(e.data))}catch{}};ws.onclose=()=>{setConn(false);setTimeout(connect,2500)};ws.onerror=()=>ws.close()}
async function events(){try{const r=await fetch(apiPath('/api/events'));const j=await r.json();const list=$('#events');if(!j.events?.length){list.innerHTML='<div class="muted">No events yet.</div>';return}list.innerHTML=j.events.slice(0,12).map(e=>`<div class="event ${e.type==='ALERT_TRIGGERED'?'alert':'safe'}"><b>${String(e.type||'EVENT').replaceAll('_',' ')}</b><span>${e.message||''} · ${e.time_iso||''}</span></div>`).join('')}catch{}}
$('#arm').onclick=async()=>{try{await fetch(apiPath('/api/arm'),{method:'POST'});status();events()}catch{}};$('#home').onclick=async()=>{try{await fetch(apiPath('/api/heartbeat'),{method:'POST'});status()}catch{}};$('#refresh').onclick=events;
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferred=e;$('#install').hidden=false});$('#install').onclick=async()=>{if(deferred){deferred.prompt();await deferred.userChoice;deferred=null;$('#install').hidden=true}};
const modal=$('#modal');$('#settings').onclick=()=>{modal.hidden=false;$('#api').value=localStorage.getItem('wiiew_api')||'';$('#phone-name').value=localStorage.getItem('wiiew_phone_name')||'My Phone'};$('#close').onclick=()=>modal.hidden=true;$('#debounce').oninput=e=>$('#debounce-out').textContent=e.target.value;$('#grace').oninput=e=>$('#grace-out').textContent=e.target.value;
$('#save').onclick=async()=>{const val=$('#api').value.trim().replace(/\/$/,'');if(val)localStorage.setItem('wiiew_api',val);else localStorage.removeItem('wiiew_api');localStorage.setItem('wiiew_phone_name',$('#phone-name').value.trim()||'My Phone');$('#settings-msg').textContent='Saved. Connecting…';modal.hidden=true;connect();status()};
async function enablePush(){if(!('serviceWorker'in navigator)||!('PushManager'in window)){alert('Push notifications are not supported by this browser.');return}try{const reg=await navigator.serviceWorker.ready;const keyRes=await fetch(apiPath('/api/push/public-key'));const {publicKey}=await keyRes.json();const perm=await Notification.requestPermission();if(perm!=='granted')return;const sub=await reg.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:base64ToUint8(publicKey)});await fetch(apiPath('/api/push/subscribe'),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(sub)});$('#settings-msg').textContent='Notifications enabled.'}catch(e){$('#settings-msg').textContent='Could not enable notifications: '+e.message}}
function base64ToUint8(s){const pad='='.repeat((4-s.length%4)%4),raw=atob((s+pad).replace(/-/g,'+').replace(/_/g,'/'));return Uint8Array.from(raw,c=>c.charCodeAt(0))}$('#push').onclick=enablePush;
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(console.warn);
if(stored){}else if(location.hostname.endsWith('github.io'))setTimeout(()=>$('#modal').hidden=false,450);
status();events();connect();setInterval(status,10000);